### PR TITLE
Extend the functionality of Peer Group Templates

### PR DESCRIPTION
**Pull request by grahamjohnston**
While the current BGP Models app is functional, I find that it can get redundant as it currently requires all Peerings/EndPoints to be defined against a RoutingInstance. This means that even when I have a network of a 100 route reflector clients that all implement the same peer group configuration, which would include address families and peers(route reflector servers), I currently have to define that router by router. My fork/PR was a quick attempt at creating PeerGroupTemplateEndpoint and PeerGroupTemplateAddressFamily models. With these models I believe that I can define more of the peer group configuration at the PeerGroupTemplate level and associate those PGTs to a RoutingInstance. I chose to create a PeerGroupTemplateEndpoint as with the way that the PGT template works, I can only reference the remote side of the peer, thus I can't create a PeerGroupTemplatePeering model that has both an A and Z endpoint. This doesn't both me with how I expect to interact with the data.

I think the UI and model interaction is functional, i.e. free from glaring horrible errors, but I certainly didn't write test code yet or anything like that. My work is mostly a copy/paste/modify of existing models that were close to what I wanted; primarily I stole from two PeerGroup* models. I'm sure I have some gaps in code, potentially related to "extra attributes"; in fact I just found a bug there where the page doesn't load. 

Warning: code written by network engineer, who also codes, and not a software developer.

### CODE REVIEW

**Comment by mzbroch** [comment]
Thanks for submitting the issue and creating Your PR! There are a few things I wanted to understand before proceeding. 
I understand we would go into a modeling direction, where a `PeerEndpoint` is considered device-level instead of per peering-level ? 

So instead of having `(device1, interface) <--> (device2, interface)`, we could have following structure:
```
endpoints:
  - [1] route reflector server, interface
  - [2] rr client, interface
  - [3] rr client, interface
peerings:
  - 1 <> 2
  - 1 <> 3
```

One of the design motivations was to provide per peering granularity. In case of re-usable endpoints, we could potentially impact many peerings. This is actually a tradeoff, where modeling (data storage) might impact data population as it can become tedious.

For the data population, I would like to understand more use cases provided by this proposed change. I think for route-reflector and 100s of peering population, a View with a Job that would allow to perform the same without object manipulation would also be a good option.

**Comment by grahamjohnston** [comment]
Hi. 

Yes, I'm suggesting that we allow for the definition of a PeerEndpoint without it being tied to a Peering. The key to the efficiency that I am after is that these PeerEndpoint would be defined against a PeerGroupTemplate. That PeerGroupTemplate would then be associated to a RoutingInstance by way of creating a PeerGroup based on the PeerTemplate. Operationally, the way I'd like the PeerGroupTemplate, and it's associated objects to work is that if it the PeerGroupTemplate was later updated to include a new PeerEndpoint, plausibly because a new router is being activated, that the RoutingInstances that have an association to that PeerGroupTemplate would also have an association to the newly define PeerEnndpoint.

Yes, there may be other ways to associate this. A Job could batch create them, and I guess the question is how easy is it for people who are minimally familiar with the system to work through that kind of process as compared to just adding a PeerEndpoint to a PeerGroupTemplate. 

Part of my argument here is that the PeerGroupTemplate is barely of value as it doesn't capture peers.

**Comment by grahamjohnston** [comment]
What happens when I need to do a mass update? Maybe it's a routing policy,
maybe it's an I'm change? Is it a case of mass delete, mass create?

Being frank, part of me feels like you guys are experiencing escalation of
commitment to what you envisioned rather than something that actually
lowers the level of effort to manage a complex network long term. Who knows
maybe I'm way off base and there are large systems using this app without
issue and I'm just picky; I don't have that visibility.

**Comment by mzbroch** [comment]
> What happens when I need to do a mass update? Maybe it's a routing policy, maybe it's an IP change? Is it a case of mass delete, mass create?

I understand concerns about lots of possibilities, however I would like to understand workflow and then propose an interface.  - What is Your routing policy, how it is defined and how often do You edit it and push mass changes? How often do You change IP addresses in peerings? Is it a part of network refresh, new pop build etc? How often do You mass create and mass delete?

Foundation for mass edit is already implemented via "peer endpoint view" - https://demo.nautobot.com/plugins/bgp/peer-endpoints/ - Endpoints Mass Edit can be a thing (although not yet exposed)

I proposed a concrete serious solution regarding importing. I would like to understand, what was wrong about it? The problem with common data model is that You cannot have everything: flexible import, strict schema, data validation, flexible views, flexible mass edits etc.

Regarding Your other concerns and comments: I am offering to help here and definitely not experiencing any kind of escalations.

**Pull request closed without merging**
